#!/usr/bin/env python
ip_addr = input('Please enter an IP address: ')
octets = ip_addr.split('.')
print(octets)
octet1_bin = bin(int(octets[0]))
octet2_bin = bin(int(octets[1]))
octet3_bin = bin(int(octets[2]))
octet4_bin = bin(int(octets[3]))
print(octet1_bin,octet2_bin,octet3_bin,octet4_bin,)
octet1_hex = hex(int(octets[0]))
octet2_hex = hex(int(octets[1]))
octet3_hex = hex(int(octets[2]))
octet4_hex = hex(int(octets[3]))
print('\n')
print('octet1'.center(12),'octet2'.center(12),'octet3'.center(12),'octet4'.center(12))
print('-' * 48)
print('{:^12}{:^12}{:^12}{:^12}'.format(*octets))
print('{:^12}{:^12}{:^12}{:^12}'.format(octet1_bin,octet2_bin,octet3_bin,octet4_bin))
print('{:^12}{:^12}{:^12}{:^12}'.format(octet1_hex,octet2_hex,octet3_hex,octet4_hex))
#print('{:>10}{:>10}{:>10}{:>10}'.format(*octets))
print('-' * 48)
